# Generated by Django 2.0.4 on 2019-03-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eresource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.CharField(choices=[('a', 'Link'), ('img', 'Image'), ('con', 'Connection')], max_length=50)),
                ('url', models.TextField(blank=True, max_length=2000, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('param', models.TextField(blank=True, max_length=2000, null=True)),
                ('request_headers', models.TextField(blank=True, max_length=3000, null=True)),
                ('response_headers', models.TextField(blank=True, max_length=3000, null=True)),
                ('mail_leakage', models.CharField(blank=True, max_length=20, null=True)),
                ('redirects_to_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('redirects_to_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_end_of_chain', models.BooleanField(default=True)),
                ('is_start_of_chain', models.BooleanField(default=True)),
                ('possible_unsub_link', models.BooleanField(default=False)),
                ('diff_eresource',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diff',
                                   to='mailfetcher.Eresource')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
                ('message_id', models.TextField()),
                ('body_plain', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('h_x_original_to', models.CharField(blank=True, max_length=200, null=True)),
                ('h_from', models.CharField(blank=True, max_length=200, null=True)),
                ('h_to', models.CharField(blank=True, max_length=200, null=True)),
                ('h_cc', models.CharField(blank=True, max_length=200, null=True)),
                ('h_bcc', models.CharField(blank=True, max_length=200, null=True)),
                ('h_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('h_date', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('h_user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('suspected_spam', models.BooleanField(default=False)),
                ('processing_state', models.CharField(
                    choices=[('UNPROCESSED', 'unprocessed'), ('VIEWED', 'viewed'), ('LINK_CLICKED', 'link_clicked'),
                             ('DONE', 'done'), ('NO_UNSUBSCRIBE_LINK', 'no_unsubscribe_link'), ('FAILED', 'failed')],
                    default='UNPROCESSED', max_length=20)),
                ('processing_fails', models.IntegerField(default=0)),
                ('identity', models.ManyToManyField(related_name='message', to='identity.Identity')),
                ('mail_from_another_identity',
                 models.ManyToManyField(related_name='_mail_mail_from_another_identity_+', to='mailfetcher.Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='eresource',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='mailfetcher.Thirdparty'),
        ),
        migrations.AddField(
            model_name='eresource',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailfetcher.Mail'),
        ),
        migrations.AddField(
            model_name='eresource',
            name='redirects_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect',
                                    to='mailfetcher.Eresource'),
        ),
    ]
