# Generated by Django 2.0.4 on 2019-03-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailfetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='resultsdirty',
            field=models.BooleanField(default=True),
        ),
    ]
