# Generated by Django 2.1.7 on 2019-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0003_auto_20190326_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eresource',
            name='mail_leakage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
