# Generated by Django 2.1.7 on 2019-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0004_auto_20190326_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='eresource',
            name='personalised',
            field=models.BooleanField(default=False),
        ),
    ]
