# Generated by Django 2.1.7 on 2019-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0005_eresource_personalised'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='possible_AB_testing',
            field=models.BooleanField(default=False),
        ),
    ]
