# Generated by Django 2.1.7 on 2019-04-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0006_mail_possible_ab_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eresource',
            name='type',
            field=models.CharField(choices=[('a', 'Link'), ('img', 'Image'), ('con', 'Connection'), ('con_click', 'Connection_clicked'), ('link', 'css'), ('script', 'JavaScript')], max_length=50),
        ),
    ]
