# Generated by Django 2.1.7 on 2019-04-05 13:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0008_mail_contains_javascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='sector',
            field=models.CharField(choices=[('tracker', 'Tracking / Advertising'), ('cdn', 'Hosting / Content Distribution'), ('altdomain', 'Alternative Domain of first party'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
