# Generated by Django 2.1.7 on 2019-04-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_service_add_advertising_option'),
        ('mailfetcher', '0009_thirdparty_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.Service'),
        ),
    ]
