# Generated by Django 2.1.7 on 2019-04-08 13:21

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def forward_func(apps, schema_editor):
    # Function that will be run when the migration is run forward.
    Service = apps.get_model("identity", "Service")
    Thirdparty = apps.get_model("mailfetcher", "Thirdparty")

    for tp in Thirdparty.objects.all():
        try:
            ser = Service.objects.get(url=tp.host)
            tp.service = ser
            tp.save()
        except ObjectDoesNotExist:
            continue


def reverse_func(apps, schema_editor):
    # Function that will be run when the migration is reversed for some reason.
    Thirdparty = apps.get_model("mailfetcher", "Thirdparty")
    for tp in Thirdparty.objects.all():
        tp.service = None
        tp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0010_thirdparty_service'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
