# Generated by Django 3.1.3 on 2021-01-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0011_thirdparty_add_connections_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='similarity_processed',
            field=models.BooleanField(default=False),
        ),
    ]
