# Generated by Django 2.2.13 on 2020-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0012_auto_20201125_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='h_bcc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='h_cc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='h_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='h_from',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='h_to',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='h_user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='h_x_original_to',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='host',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
