# Generated by Django 3.1.3 on 2021-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0013_auto_20201126_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('word', models.TextField(max_length=2000)),
            ],
        ),
    ]
