# Generated by Django 2.2.19 on 2021-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfetcher', '0015_auto_20210120_1042'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eresource',
            index=models.Index(fields=['mail', 'type', 'personalised'], name='mailfetcher_mail_id_2f7069_idx'),
        ),
    ]
