# Generated by Django 2.0.4 on 2019-03-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('mailfetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicethirdpartyembeds',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailfetcher.Mail'),
        ),
        migrations.AddField(
            model_name='servicethirdpartyembeds',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeds',
                                    to='identity.Service'),
        ),
        migrations.AddField(
            model_name='servicethirdpartyembeds',
            name='thirdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='embeds', to='mailfetcher.Thirdparty'),
        ),
        migrations.AddField(
            model_name='service',
            name='thirdparties',
            field=models.ManyToManyField(related_name='services', through='identity.ServiceThirdPartyEmbeds',
                                         to='mailfetcher.Thirdparty'),
        ),
        migrations.AddField(
            model_name='identity',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.Service'),
        ),
    ]
