# Generated by Django 2.0.4 on 2019-03-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('identity', '0002_auto_20190314_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='resultsdirty',
            field=models.BooleanField(default=True),
        ),
    ]
