# Generated by Django 2.0.4 on 2019-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('identity', '0003_service_resultsdirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hasApprovedIdentity',
            field=models.BooleanField(default=False),
        ),
    ]
