# Generated by Django 2.0.4 on 2019-03-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('identity', '0004_service_hasapprovedidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicethirdpartyembeds',
            name='sets_cookie',
            field=models.BooleanField(default=False),
        ),
    ]
