# Generated by Django 2.0.4 on 2019-03-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('identity', '0006_auto_20190315_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicethirdpartyembeds',
            name='embed_type',
            field=models.CharField(choices=[('STATIC', 'static'), ('ONVIEW', 'onView'), ('ONCLICK', 'onClick'),
                                            ('UNDETERMINED', 'undetermined')], default='UNDETERMINED', max_length=20),
        ),
    ]
