# Generated by Django 2.1.7 on 2019-04-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_auto_20190401_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicethirdpartyembeds',
            name='receives_identifier',
            field=models.BooleanField(default=False),
        ),
    ]
