# Generated by Django 2.1.7 on 2019-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_servicethirdpartyembeds_receives_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
