# Generated by Django 2.1.7 on 2019-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_service_changeurltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sector',
            field=models.CharField(choices=[('activist', 'Activist'), ('adult', 'Adult'), ('ads', 'Advertising'), ('art', 'Art'), ('b2b', 'Business-to-Business'), ('entertainment', 'Entertainment'), ('finance', 'Financial'), ('games', 'Games'), ('health', 'Health'), ('news', 'News'), ('politics', 'Political Party / Politician'), ('reference', 'Reference'), ('science', 'Science'), ('shopping', 'Shopping'), ('sports', 'Sports'), ('travel', 'Travel'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
