# Generated by Django 2.1.7 on 2019-04-12 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Service = apps.get_model('identity', 'Service')
    for service in Service.objects.all().iterator():
        service.permitted_senders = [service.url]
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_service_add_advertising_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='permitted_senders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='permitted_senders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=False, size=None)
        ),
    ]
