# Generated by Django 3.1.3 on 2021-02-24 15:44

from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Identity = apps.get_model('identity', 'Identity')
    for identity in Identity.objects.all().iterator():
        if identity.approved:
            identity.is_dead = False
        else: 
            identity.is_dead = True

        identity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_service_permitted_senders'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_dead',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_my_defaults, migrations.RunPython.noop),
    ]
